[package]
name = "tokenizers" 
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","staticlib"]

[dependencies]
libc = "0.2.174"
tokenizers = {version = "0.21.4" }
cbindgen = "0.29.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.5"
#
#[[bench]]
#name = "decode_benchmark"
#harness = false
